### ISSUE TITLE
I want to run on arm architecture

### ISSUE THREAD

**Issue by KwonMinho** [0xPolygonHermez/zkevm-prover#235]
Tried to run polygon zkevm on arm architecture. (with docker)

However, the zkevm-prover component did not run. (because of cpu architecture)

I have two questions here.

 1. Why arm architecture is not supported by zkevm-prover?.. What are the challenges?

 2. Is there any way to run zkevm-prover on arm architecture?

**Comment by KwonMinho** [comment]
Sharing answers received from polygon forum.

https://forum.polygon.technology/t/question-about-how-to-run-zkevm-prover-in-an-arm-environment/10704/3

**Comment by eduadiez** [comment]
> Why arm architecture is not supported by zkevm-prover?

Mainly it's currently not supported because we have implemented optimizations only for the x86_64 architecture, especially for the case of BN128 curve since we use [ffiasm](https://github.com/iden3/ffiasm), although we also have optimizations for goldilocks with the AVX2 instruction set.

> What are the challenges?

In order to reach a performance level close to x86_64, it would be necessary to have a vectorized version with the ARM instruction set for both primes.

> Is there any way to run zkevm-prover on arm architecture?
Sorry but it's not possible at this time

Also keep in mind that ~480GB of available ram is currently required, and there are not many ARM instances with this capacity

**Comment by KwonMinho** [comment]
Interesting!!

thank you for the reply.
